version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - monitoring


  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=password"
    ports:
      - "9200:9200"
    networks:
      - monitoring


  fastapi:
    build:
      context: ./app
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - monitoring

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - monitoring

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - monitoring

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - monitoring
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=monitoring
      - INFLUXDB_USER=grafana
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_TOKEN=JfVHVfYP2DIquWyHcNrMhxcRkANQh8bsxWwEYFjvaAW7jKp_Rr5GrPDg-8zcHx1cvxHEYkuNksFdCdcLyQ7hVg==
      - INFLUXDB_ORGANISATION=main_org
      - INFLUXDB_BUCKET=main_bucket
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - monitoring

networks:
  monitoring:



# docker-compose up --build
# docker-compose down && docker-compose up --build -d
# siege -c 100 -r 100 http://localhost/

#Чтобы установить curl внутри контейнера FastAPI, попробуйте выполнить:

#docker exec -it fastapi bash
#apt update && apt install -y curl
#curl -X GET http://elasticsearch:9200

#Если не хотите устанавливать дополнительные утилиты, используйте Python:

#docker exec -it fastapi python3 -c "import requests; print(requests.get('http://elasti


#4. Поиск IP-адреса Elasticsearch в Windows (PowerShell)

#Так как команда grep не работает в PowerShell, используйте следующую команду для поиска IP-адреса Elasticsearch:

#docker inspect elasticsearch | Select-String "IPAddress"

#Если IP-адрес найден, попробуйте подключиться к нему:

#curl -X GET http://<IPAddress>:9200

#переопределение пароля еластик
#docker exec -it elasticsearch /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -i